### ISSUE TITLE
[Bug]: In SPA mode, the dropdown doesn't close itself when clicked into one of the recent records

### ISSUE THREAD

**Issue by StaffCollab** [awcodes/recently#21]
### What happened?

I believe this issue has to do with SPA mode since the page is not refreshing. In #17  you have fixed the refreshing of the spa list but  the dropdown is still not closing,

### How to reproduce the bug

Just have this installed toegther with SPA mode

### Package Version

@latest

### PHP Version

8.2

### Laravel Version

11

**Comment by awcodes** [comment]
Since this is using filaments dropdown component, I'm favoring the idea that dropdowns closing in spa mode should be handled by filament and not necessary by a plugin. It keeps behavior consistent with filament core.
