### ISSUE TITLE
[Bug]: Using awcodes/recently causing an error

### ISSUE THREAD

**Issue by RoseRiyadh** [awcodes/recently#8]
### What happened?

I tested the awcodes/recently plugin and when i added the recently class in the admin panel provider as such 
->plugins([
                RecentlyPlugin::make(),
            ])
it shows this error PanelsRenderHook is not found and when i tried to search about the location of this error it showed in the package itself. Is there any solution to this error?

### How to reproduce the bug

I expect the package to be working.

### Package Version

1.0.2

### PHP Version

8.2

### Laravel Version

9

### Which operating systems does with happen with?

macOS

**Comment by awcodes** [comment]
This plugin only works with Filament v3.
